runtime: php55

handlers:
- url: /css
  static_dir: css
- url: /fonts
static_dir: fonts
- url: /js
static_dir: js
- url: /scss
static_dir: scss
  
- url: /images/(.*\.(gif|png|jpg))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg))
  
- url: /.*
  script: single.php
- url: /.*
script: index.php